// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cartas_aifa.Data;

#nullable disable

namespace cartas_aifa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620011836_AgregarOpacidadConfigVisual")]
    partial class AgregarOpacidadConfigVisual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cartas_aifa.Models.AutoridadCarta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rango")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AutoridadesAifa");
                });

            modelBuilder.Entity("cartas_aifa.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdF")
                        .HasColumnType("int");

                    b.Property<string>("NombreCarrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdF");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("cartas_aifa.Models.ConfiguracionVisual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Alto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ancho")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AnioAplicacion")
                        .HasColumnType("int");

                    b.Property<decimal>("CoordX")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoordY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImagenId")
                        .HasColumnType("int");

                    b.Property<string>("MostrarEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Opacidad")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImagenId");

                    b.ToTable("ConfiguracionesVisuales");
                });

            modelBuilder.Entity("cartas_aifa.Models.DetalleEtapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TipoEtapa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DetallesEtapas");
                });

            modelBuilder.Entity("cartas_aifa.Models.DetallesTipoCarta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEtapa")
                        .HasColumnType("int");

                    b.Property<string>("NombreCarta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEtapa");

                    b.ToTable("DetallesTipoCarta");
                });

            modelBuilder.Entity("cartas_aifa.Models.DireccionAifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreDir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DireccionesAifa");
                });

            modelBuilder.Entity("cartas_aifa.Models.DirectorEscolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdF")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rango")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdF");

                    b.ToTable("DirectoresEscolares");
                });

            modelBuilder.Entity("cartas_aifa.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdF")
                        .HasColumnType("int");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdF");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("cartas_aifa.Models.EtapaAifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDetalleEtapa")
                        .HasColumnType("int");

                    b.Property<int>("IdDireccion")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdSubdireccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDetalleEtapa");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdSubdireccion");

                    b.ToTable("EtapasAifa");
                });

            modelBuilder.Entity("cartas_aifa.Models.Facultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdU")
                        .HasColumnType("int");

                    b.Property<string>("NombreF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdU");

                    b.ToTable("Facultades");
                });

            modelBuilder.Entity("cartas_aifa.Models.ImagenCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImagenesCatalogo");
                });

            modelBuilder.Entity("cartas_aifa.Models.Leyenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alineacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CoordX")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoordY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EstiloFuente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("MostrarEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TamanoFuente")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leyendas");
                });

            modelBuilder.Entity("cartas_aifa.Models.PiePagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alineacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorFondo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorLetra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorLinea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<float>("GrosorLinea")
                        .HasColumnType("real");

                    b.Property<string>("MostrarEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TamanoFuente")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TieneLinea")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PiesDePagina");
                });

            modelBuilder.Entity("cartas_aifa.Models.SubdireccionAifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDir")
                        .HasColumnType("int");

                    b.Property<string>("NombreSub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDir");

                    b.ToTable("SubdireccionesAifa");
                });

            modelBuilder.Entity("cartas_aifa.Models.TramiteAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EtapaAifaId")
                        .HasColumnType("int")
                        .HasColumnName("EtapaAifa_Id");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdAut")
                        .HasColumnType("int");

                    b.Property<int>("IdDetalleEtapa")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoCarta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.HasIndex("IdAut");

                    b.HasIndex("IdDetalleEtapa");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdTipoCarta");

                    b.ToTable("TramitesAcademicos");
                });

            modelBuilder.Entity("cartas_aifa.Models.Universidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Universidades");
                });

            modelBuilder.Entity("cartas_aifa.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("cartas_aifa.Models.Carrera", b =>
                {
                    b.HasOne("cartas_aifa.Models.Facultad", "Facultad")
                        .WithMany()
                        .HasForeignKey("IdF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("cartas_aifa.Models.ConfiguracionVisual", b =>
                {
                    b.HasOne("cartas_aifa.Models.ImagenCatalogo", "Imagen")
                        .WithMany()
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("cartas_aifa.Models.DetallesTipoCarta", b =>
                {
                    b.HasOne("cartas_aifa.Models.DetalleEtapa", "DetalleEtapa")
                        .WithMany("TiposDeCartas")
                        .HasForeignKey("IdEtapa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetalleEtapa");
                });

            modelBuilder.Entity("cartas_aifa.Models.DirectorEscolar", b =>
                {
                    b.HasOne("cartas_aifa.Models.Facultad", "Facultad")
                        .WithMany()
                        .HasForeignKey("IdF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("cartas_aifa.Models.Estudiante", b =>
                {
                    b.HasOne("cartas_aifa.Models.Facultad", "Facultad")
                        .WithMany()
                        .HasForeignKey("IdF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("cartas_aifa.Models.EtapaAifa", b =>
                {
                    b.HasOne("cartas_aifa.Models.DetalleEtapa", "DetalleEtapa")
                        .WithMany()
                        .HasForeignKey("IdDetalleEtapa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cartas_aifa.Models.DireccionAifa", "Direccion")
                        .WithMany()
                        .HasForeignKey("IdDireccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cartas_aifa.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cartas_aifa.Models.SubdireccionAifa", "Subdireccion")
                        .WithMany()
                        .HasForeignKey("IdSubdireccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetalleEtapa");

                    b.Navigation("Direccion");

                    b.Navigation("Estudiante");

                    b.Navigation("Subdireccion");
                });

            modelBuilder.Entity("cartas_aifa.Models.Facultad", b =>
                {
                    b.HasOne("cartas_aifa.Models.Universidad", "Universidad")
                        .WithMany()
                        .HasForeignKey("IdU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("cartas_aifa.Models.SubdireccionAifa", b =>
                {
                    b.HasOne("cartas_aifa.Models.DireccionAifa", "Direccion")
                        .WithMany()
                        .HasForeignKey("IdDir")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("cartas_aifa.Models.TramiteAcademico", b =>
                {
                    b.HasOne("cartas_aifa.Models.AutoridadCarta", "Autoridad")
                        .WithMany()
                        .HasForeignKey("IdAut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cartas_aifa.Models.DetalleEtapa", "DetalleEtapa")
                        .WithMany()
                        .HasForeignKey("IdDetalleEtapa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cartas_aifa.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cartas_aifa.Models.DetallesTipoCarta", "TipoCarta")
                        .WithMany()
                        .HasForeignKey("IdTipoCarta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autoridad");

                    b.Navigation("DetalleEtapa");

                    b.Navigation("Estudiante");

                    b.Navigation("TipoCarta");
                });

            modelBuilder.Entity("cartas_aifa.Models.DetalleEtapa", b =>
                {
                    b.Navigation("TiposDeCartas");
                });
#pragma warning restore 612, 618
        }
    }
}
