// <auto-generated />
namespace Cartas_Aifa_Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ImagenCatalogoRequieredURL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImagenCatalogoRequieredURL));
        
        string IMigrationMetadata.Id
        {
            get { return "202603252249351_ImagenCatalogoRequieredURL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
